version: '3'

services:
  nest-simple-api:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: 'redis'
    ports:
      - '6379:6379'
